name: ASP.NET Core CI

on:
  push:
    branches:
      - master
  schedule:
    - cron 0 15 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100-preview6-012264
    - name: Build with dotnet
      run: dotnet publish --configuration Release
